
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LuisB
 */
public class main extends javax.swing.JFrame {
DefaultTableModel tables = new DefaultTableModel();
    private JTable JTable;
    
    public main() {
        initComponents();
        String[] titulo=new String[] {"Moneda", "Fecha", "Tipo de cambio"};
        tables.setColumnIdentifiers(titulo);
        jTable1.setModel(tables);
    }
    String resultConversion;
    double resultConvDigito;
    void agregar() {
    
        tables.addRow(new Object[] {
            monedasPaises.getSelectedItem(),fecha.getText(), resultConversion
        });
      

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fecha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        pesos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        monedasPaises = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnADD = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Moneda", "Fecha", "Tipo de cambio"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        fecha.setText("00 / 00 / 0000");

        jLabel1.setText("Fecha");

        pesos.setText("0");

        jLabel2.setText("Ingrese la cantidad de pesos");

        monedasPaises.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolar", "Euro", "Chile", "Argentino", "Yen", "Cop", "Dolar_Canadiense", "Won", "Yuan", "Real_brasileño", " ", " ", " " }));
        monedasPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monedasPaisesActionPerformed(evt);
            }
        });

        jLabel3.setText("Conversión");

        btnADD.setText("Agregar");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("CONVERSOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnADD)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(59, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(pesos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(monedasPaises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(monedasPaises, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnADD)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        double dolar = 0.050;
        double chile = 48.83;
        double euro = 0.051; 
        double yen = 7.48;
        double argentino = 7.62483;
        double Cop = 0.0040;
        double Dolar_canadiense = 14.50;
        double won = 72.12;
        double Yuan = 2.71;
        double real_brasileño = 3.83;
        

        
        
       String datoPesosIngresados = pesos.getText();
       int datoPesoPaisIngresadosInt = Integer.parseInt(datoPesosIngresados);
        
        
        String moneda= "";
        
        if ("Dolar".equals(monedasPaises.getSelectedItem())){
              moneda = "1";
           }
                if ("Euro".equals(monedasPaises.getSelectedItem())){
              moneda = "2";
           }
                        if ("Chile".equals(monedasPaises.getSelectedItem())){
               moneda = "3";
           }
                                if ("Argentino".equals(monedasPaises.getSelectedItem())){
              moneda = "4";
           }
                                        if ("Yen".equals(monedasPaises.getSelectedItem())){
              moneda = "5";
           }
                                            if ("Cop".equals(monedasPaises.getSelectedItem())){
              moneda = "6";
           }
                                                if ("Won".equals(monedasPaises.getSelectedItem())){
              moneda = "8";
           }
                                                    if ("Yuan".equals(monedasPaises.getSelectedItem())){
              moneda = "9";
           }
                                                        if ("real brasileño".equals(monedasPaises.getSelectedItem())){
              moneda = "10";
           }
                                                
       int monedaInt = Integer.parseInt(moneda);
        
      
       if(monedaInt == 1){
        resultConvDigito = datoPesoPaisIngresadosInt * dolar;
         resultConversion = Math.round(resultConvDigito) + " dolares.";
       }
       if(monedaInt == 2){
         
         resultConvDigito = datoPesoPaisIngresadosInt * chile;
         resultConversion = Math.round(resultConvDigito) + " peso Chileno.";
       }
       if(monedaInt == 3){
         resultConvDigito = datoPesoPaisIngresadosInt * euro;
           resultConversion = Math.round(resultConvDigito) + " euros.";
       }
       if(monedaInt == 4){
         resultConvDigito = datoPesoPaisIngresadosInt * yen;
         resultConversion = Math.round(resultConvDigito) + " Yen.";
       }
       if(monedaInt == 5){
         resultConvDigito = datoPesoPaisIngresadosInt * argentino;
         resultConversion = Math.round(resultConvDigito) + " Peso argentino.";
       }
         if(monedaInt == 6){
         resultConvDigito = datoPesoPaisIngresadosInt * Cop;
         resultConversion = Math.round(resultConvDigito) + " Peso colombiano.";
       }
       if(monedaInt == 7){
       resultConvDigito = datoPesoPaisIngresadosInt * Dolar_canadiense;
         resultConversion = Math.round(resultConvDigito) + " Dolar canadiense.";
       }
       if(monedaInt == 8){
        resultConvDigito = datoPesoPaisIngresadosInt * won;
         resultConversion = Math.round(resultConvDigito) + " Won.";
       }
       if(monedaInt == 9){
        resultConvDigito = datoPesoPaisIngresadosInt * Yuan;
         resultConversion = Math.round(resultConvDigito) + " yuan.";
       }
      if(monedaInt == 10){
         resultConvDigito = datoPesoPaisIngresadosInt * real_brasileño;
         resultConversion = Math.round(resultConvDigito) + " real brasileño";
       }

       agregar();
        
        
    }//GEN-LAST:event_btnADDActionPerformed

    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void jTable1AncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorMoved

    private void monedasPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monedasPaisesActionPerformed
        
        
    }//GEN-LAST:event_monedasPaisesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JTextField fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> monedasPaises;
    private javax.swing.JTextField pesos;
    // End of variables declaration//GEN-END:variables

    private static class jTable {

        public jTable() {
        }
    }

  
}
