package prueba;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Tomgh
 */
public class si extends javax.swing.JFrame {

    /**
     * Creates new form si
     */
    public si() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtApellidoPaternoEntrada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtApellidoMaternoDato = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        cbxGenero = new javax.swing.JComboBox<>();
        cbxEntidad1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        resultadoCurp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn.setText("Guardar");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        jLabel3.setText("nombre(s)");

        txtApellidoPaternoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPaternoEntradaActionPerformed(evt);
            }
        });

        jLabel1.setText("apellido paterno");

        txtApellidoMaternoDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoMaternoDatoActionPerformed(evt);
            }
        });

        jLabel2.setText("apellido materno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtApellidoMaternoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtApellidoPaternoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtApellidoPaternoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoMaternoDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        txtDia.setText("00");
        txtDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaActionPerformed(evt);
            }
        });

        txtMes.setText("00");

        txtAnio.setText("0000");

        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HOMBRE\t", "MUJER" }));

        cbxEntidad1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Coahuila de Zaragoza", "Colima", "Chiapas", "Chihuahua", "Distrito Federal", "Durango", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "México", "Michoacán de Ocampo", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz de Ignacio de la Llave", "Yucatán", "Zacatecas", "Nacido en el Extranjero" }));
        cbxEntidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEntidad1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("GENERADOR DE CURP ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(resultadoCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 395, Short.MAX_VALUE)
                        .addComponent(btn)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbxEntidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(cbxEntidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(resultadoCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(btn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
  String apellidoPaternoDato = txtApellidoPaternoEntrada.getText().toUpperCase();
        
char[] apellidoPaternoChar = apellidoPaternoDato.toCharArray();
char apellidoPaternoDigito = apellidoPaternoChar[0];


String cadena = apellidoPaternoDato.substring(0,1);

boolean vocal = false;
        int i = 0;
        while(i < apellidoPaternoDato.length()&! vocal){
            if ((apellidoPaternoDato.charAt(i) == 'A')||
                    (apellidoPaternoDato.charAt(i) == 'E')||
                    (apellidoPaternoDato.charAt(i) == 'I')||
                    (apellidoPaternoDato.charAt(i) == 'O')||
                    (apellidoPaternoDato.charAt(i) == 'U')){
                cadena = cadena+apellidoPaternoDato.charAt(i);
                vocal = true;
            }
            i ++;
        }

   //consigue la primera letra del apellido materno


   String apellidoMaternoDato = txtApellidoMaternoDato.getText().toUpperCase();

  String apellidosJuntos = apellidoPaternoDato + " " + apellidoMaternoDato;
  
     String [] apellidosSeparados = apellidosJuntos.split(" ");
     
     int numeroApellidos = apellidosSeparados.length;
     
     String numeroApellidosString = String.valueOf(numeroApellidos);

     String apellidoMaternoDigito ;
     
     if (numeroApellidos <= 1){
     
          apellidoMaternoDigito = "X";  
     } 
     else{
      
      char[] apellidoMaternoChar = apellidoMaternoDato.toCharArray();
      char apellidoMaternoDigitoChar2 = apellidoMaternoChar[0];
      apellidoMaternoDigito = String.valueOf(apellidoMaternoDigitoChar2);
     }
 //primera letra nombre
       String nombreDato = txtNombre.getText().toUpperCase();
        
char[] nombreChar = nombreDato.toCharArray();
char nombreDigito = nombreChar[0];

String nombreDatoSi = nombreDato.substring(0,1);
     

     /// FECHA SI

     String numeroAnio = txtAnio.getText();
          String numeroMes = txtMes.getText();
               String numeroDia = txtDia.getText();
  

char[] numeroAnio1 = numeroAnio.toCharArray();
char numeroAnioDigito2 = numeroAnio1[2];
char numeroAnioDigito3 = numeroAnio1[3];

String anioCompleto = numeroAnioDigito2 + "" + numeroAnioDigito3 + "" ;
 
     
     //GENERO SI
String generoSeleccionado = cbxGenero.getSelectedItem().toString();

char[] letraGenero1 = generoSeleccionado.toCharArray();
char generoSeleccionado1 = letraGenero1[0];

//Entidad federativa SI
            javax.swing.DefaultComboBoxModel entidadSeleccionada = (DefaultComboBoxModel) cbxEntidad1.getModel();

                 String clave = "";

            if ("Aguascalientes".equals(entidadSeleccionada.getSelectedItem())){
                        clave="AS";
            }
            else  if ("Baja California".equals(entidadSeleccionada.getSelectedItem())){	
               clave="BC";
           }else if("Baja California Sur".equals(entidadSeleccionada.getSelectedItem())){
               clave="BS";
           }else if ("Campeche".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"CC";
           }else if("Coahuila de Zaragoza".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"CL";
           }else if("Colima".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"CM";
           }else if("Chiapas".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"CS";
           }else if("Chihuahua".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"CH";
           }else if("Distrito Federal".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"DF";
           }else if("Durango".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"DG";
           }else if("Guanajuato".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"GT";
           }else if("Guerrero".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"GR";
           }else if("Hidalgo".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"HG";
           }else if("Jalisco".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"JC";
           }else if("México".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"MC";
           }else if("Michoacán de Ocampo".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"MN";
           }else if ("Morelos".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"MS";
           }else if("Nayarit".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"NT";
           }else if("Nuevo León".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"NL";
           }else if("Oaxaca".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"OC";
           }else if("Puebla".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"PL";
           }else if("Querétaro".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"QT";
           }else if("Quintana Roo".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"QR";
           }else if("San Luis Potosí".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"SP";
           }else if("Sinaloa".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"SL";
           }else if("Sonora".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"SR";
           }else if("Tabasco".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"TC";
           }else if("Tamaulipas".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"TS";
           }else if("Tlaxcala".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"TL";
           }else if("Veracruz de Ignacio de la Llave".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"VZ";
           }else if("Yucatán".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"YN";
           }else if("Zacatecas".equals(entidadSeleccionada.getSelectedItem())){
               clave=	"ZS";
           }else if("Nacido en el Extranjero".equals(entidadSeleccionada.getSelectedItem())){
               clave="NE";
           }else {
JOptionPane.showMessageDialog(null, "Te falto llenar nacionalidad","Error", JOptionPane.ERROR_MESSAGE);
           }

//consonante de apellido paterno


            String apellidoPaternoConsonante = apellidoPaternoDato.replace("Á", "").replace("É", "").replace("Í", "").replace("Ó", "").replace("Ú", "").replace("A", "").replace("E", "").replace("I", "").replace("O", "").replace("U", "");
            char [] apellidoPaternoConsonanteChar = apellidoPaternoConsonante.toCharArray();
            char   apellidoPaternoConsonanteDato = apellidoPaternoConsonanteChar[1];
            
            //Sacar Primera consonante interna (no inicial) del segundo apellido. En caso de no tener segundo apellido, se colocará X.
            String apellidoMaternoConsonante = apellidoMaternoDato.replace("A", "").replace("E", "").replace("I", "").replace("O", "").replace("U", "").replace("Á", "").replace("É", "").replace("Í", "").replace("Ó", "").replace("Ú", "");
            String apellidoMaternoConsonanteDato="";
            if (numeroApellidos <= 1){
                       apellidoMaternoConsonanteDato = "X"; 
    System.out.print(apellidoMaternoConsonanteDato);
                    }else{
                    char [] apellidoMaternoConsonanteChar = apellidoMaternoConsonante.toCharArray();
                    char apellidoMaternoConsonanteDato1 = apellidoMaternoConsonanteChar[1];
                    apellidoMaternoConsonanteDato = String.valueOf(apellidoMaternoConsonanteDato1);
            }
            
            //consonante nombre
            String nombreConsonante = nombreDato.replace("Á", "").replace("É", "").replace("Í", "").replace("Ó", "").replace("Ú", "").replace("A", "").replace("E", "").replace("I", "").replace("O", "").replace("U", "");
            char [] nombreConsonanteChar = nombreConsonante.toCharArray();
            char   nombreConsonanteDato = nombreConsonanteChar[1];
            

            //si es mayor a 2000 "A" y si es menor "0"
        int anio = Integer.parseInt(numeroAnio);
    String anioDato = "";
     if (anio <= 1999){
     
          anioDato = "0";  
     } 
     else{
     
         anioDato = "A";
         
     }
            // 1
            String uno = "1";

            
//              System.out.println(cadena + apellidoMaternoDigito + "" + nombreDatoSi + "" + anioCompleto + numeroMes + numeroDia + generoSeleccionado1 + "" + clave + "" + apellidoPaternoConsonanteDato + "" + apellidoMaternoConsonanteDato + "" + nombreConsonanteDato + anioDato + uno);
resultadoCurp.setText(cadena + apellidoMaternoDigito + "" + nombreDatoSi + "" + anioCompleto + numeroMes + numeroDia + generoSeleccionado1 + "" + clave + "" + apellidoPaternoConsonanteDato + "" + apellidoMaternoConsonanteDato + "" + nombreConsonanteDato + anioDato + uno);
    }//GEN-LAST:event_btnActionPerformed

    private void txtApellidoPaternoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPaternoEntradaActionPerformed

        
        
       
        
        
       
    }//GEN-LAST:event_txtApellidoPaternoEntradaActionPerformed

    private void txtApellidoMaternoDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoMaternoDatoActionPerformed
//apellido materno el programa toma la primera vocal del apellido materno en caso de no tener se mostrara una "X"






        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoMaternoDatoActionPerformed

    private void txtDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaActionPerformed

    private void cbxEntidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEntidad1ActionPerformed



        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEntidad1ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(si.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(si.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(si.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(si.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new si().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JComboBox<String> cbxEntidad1;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel resultadoCurp;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtApellidoMaternoDato;
    private javax.swing.JTextField txtApellidoPaternoEntrada;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
